parameters:
#    evry_thing_utilisateur.example.class: EvryThing\UtilisateurBundle\Example

services:
#    evry_thing_utilisateur.example:
#        class: %evry_thing_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
